add_newline = false
format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "red"
format = '([$all_status$ahead_behind]($style) )'

[nodejs]
symbol = " "
format = '[$symbol($version )]($style)'
style = "green"

[python]
symbol = " "
format = '[$symbol($version )(\($virtualenv\) )]($style)'
style = "yellow"

[cmd_duration]
min_time = 1000
format = "took [$duration](bold yellow) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

